name: Deployment-SixT

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Create deployment package
        run: |
          mkdir deployment
          docker create --name temp_container ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
          docker cp temp_container:/app/ ./deployment
          docker rm temp_container
        
      - name: Deploy to S3
        run: |
          aws s3 sync ./deployment s3://${{ secrets.S3_BUCKET_NAME }}/deployment/ --delete
